# Generated by Django 3.0.8 on 2020-07-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200714_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance_usd',
            field=models.IntegerField(default=0),
        ),
    ]
