# Generated by Django 3.1 on 2020-08-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200715_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_messages',
            field=models.BooleanField(default=True),
        ),
    ]
