# Generated by Django 3.1 on 2020-08-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_show_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='domain',
            new_name='subdomain',
        ),
    ]
