# Generated by Django 3.1 on 2020-08-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200811_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advanceduser',
            old_name='domain',
            new_name='subdomain',
        ),
    ]
