# Generated by Django 3.0.8 on 2020-07-13 06:46

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', sorl.thumbnail.fields.ImageField(default='commodities_pics/default.jpg', upload_to='commodities_pics')),
                ('on_the_market', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile')),
            ],
        ),
    ]
