# Generated by Django 3.0.8 on 2020-07-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
