# Generated by Django 3.1 on 2020-08-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20200818_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='commodity',
        ),
    ]
