# Generated by Django 3.1 on 2020-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_purchase_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'READY'), (1, 'AWAITING'), (2, 'APPROVED'), (3, 'DONE')], default=0),
        ),
    ]
