# Generated by Django 3.1 on 2020-08-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_auto_20200818_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'AVAILABLE'), (1, 'AWAITING'), (2, 'APPROVED'), (3, 'DONE')], default=0),
        ),
    ]
